apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8singress
metadata:
  name: k8singress
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Ingress"]
