apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8singress
metadata:
  name: psp-ingress
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["ingress"]
